### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by capesean** [edc-it/MEInsight#6]
I tried to login to the M&E Insight demo but I get an "Invalid login attempt" error message.

I tried sending a mail to meinsight@edc.org but received the response: The group meinsight only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.

**Comment by mmahomar** [comment]
Hi Sean, thanks for letting us know! We've fixed the login issue and requested that meinsight@edc.org be allowed to receive external emails.

**Comment by capesean** [comment]
I still can't log in 😢 
Am I on the right page: https://meinsight.edc.org/Identity/Account/Login
Should the login be an email address?

**Comment by capesean** [comment]
All sorted - I downloaded the repo and ran it locally with the `admin@meinsight.edc.org` login and it worked.
